### ISSUE TITLE
cli: add "--force" option

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-queues#5]
To avoid errors like `amqp.exceptions.NotFound: Queue.purge: (404) NOT_FOUND - no queue 'stats-record-view' in vhost '/'`, a `--force` could be added (similar to `invenio index init --force`), which would ignore errors. 

This is especially useful for `setup` scripts, which have to "reset" the environment by cleaning up any existing fixtures.

Scenarios to check:

- [x] Create a queue that already exists (shouldn't do anything actually)
- [x] You have already e.g. one queue `foo`, you have created it (via `invenio queues declare`), and then you add another queue `bar`, and you want to create it as well via `invenio queues declare` (of course, still keep the `foo` queue)
- [x] You want to delete/purge all the queues, but you are in a partial state: e.g. you have configured `foo` and `bar`, but only `foo` is actually created, and then you want to run `invenio queues delete`, and end up with no queues at all

**Comment by frankois** [comment]
| Command |                                |                    | Comment                                                      |
| ------- | ------------------------------ | ------------------ | ------------------------------------------------------------ |
| Declare | configured queues not running  | :white_check_mark: |                                                              |
|         | configured queues running      | :white_check_mark: |                                                              |
|         | specific queue already running | :white_check_mark: |                                                              |
|         | partial state                  | :white_check_mark: |                                                              |
|         |                                |                    |                                                              |
| Delete  | configured queues running      | :white_check_mark: |                                                              |
|         | configured queues not running  | :white_check_mark: |                                                              |
|         | specific queues not running    | :white_check_mark: |                                                              |
|         | in partial state               | :white_check_mark: |                                                              |
|         |                                |                    |                                                              |
| Purge   | configured queues running      | :white_check_mark: |                                                              |
|         | specific queues not running    | :x:                | `amqp.exceptions.NotFound: Queue.purge: (404) NOT_FOUND - no queue 'stats-record-view' in vhost '/'` |
|         | configured queues not running  | :x:                | =                                                            |
|         | in partial state               | :x:                | =                                                            |

**Comment by slint** [comment]
Closed via #11
